Update pre-request scripts to mitigate concurrent modification issue while removing blank headers
In Postman 10.7.1 for MacOS, `pm.request.headers.each()` fails when removing headers while iterating over them:
> TypeError: Cannot read properties of undefined (reading 'value')

Using `pm.request.forEachHeader()` avoids that pitfall.  Other options would be operating on `pm.request.headers.members`, or calling `all()` or `map()` before `each()`, since either would result in an independent list of headers.

Reference: https://www.postmanlabs.com/postman-collection/Request.html#forEachHeader